dist: trusty

language: node_js

node_js:
  # - "0.12"
  # - "4.0"
  # - "4"
  # - "5"
  - "stable"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

sudo: required

script:
  - npm test

env:
  - TRAVIS=travis CXX=g++-4.8
